// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Metadata.Models_DB;

[Table("API_Logging")]
public partial class ApiLogging
{
    [Key]
    [Column("Transaction_ID")]
    public int TransactionId { get; set; }

    [Column("Application_Name")]
    [StringLength(200)]
    [Unicode(false)]
    public string ApplicationName { get; set; }

    [Column("Requesting_System")]
    [StringLength(250)]
    [Unicode(false)]
    public string RequestingSystem { get; set; }

    [Column("API_Method")]
    [StringLength(500)]
    [Unicode(false)]
    public string ApiMethod { get; set; }

    [Column("Requesting_Start_DT", TypeName = "datetime")]
    public DateTime RequestingStartDt { get; set; }

    [Column("Requesting_End_DT", TypeName = "datetime")]
    public DateTime RequestingEndDt { get; set; }

    [Column("Error_Message")]
    [StringLength(5000)]
    [Unicode(false)]
    public string ErrorMessage { get; set; } = string.Empty;

    [Column("Request_Message")]
    [StringLength(5000)]
    [Unicode(false)]
    public string RequestMessage { get; set; } = string.Empty;

    [Column("Response_Message")]
    [StringLength(5000)]
    [Unicode(false)]
    public string ResponseMessage { get; set; }

    [Column("Debug_1")]
    [StringLength(5000)]
    [Unicode(false)]
    public string Debug1 { get; set; } = string.Empty;

    [Column("Debug_2")]
    [StringLength(5000)]
    [Unicode(false)]
    public string Debug2 { get; set; } = string.Empty;

    [Column("Return_Code")]
    [StringLength(100)]
    [Unicode(false)]
    public string ReturnCode { get; set; }
}