// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Metadata.Models_DB;
[Table("GitHub")]
public partial class GitHub
{
    [Key]
    [Column("GitHub_ID")]
    public int GitHubId { get; set; }

    [Column("Image_Source")]
    [StringLength(500)]
    [Unicode(false)]
    public string ImageSource { get; set; }

    [Column("Image_Alt")]
    [StringLength(100)]
    [Unicode(false)]
    public string ImageAlt { get; set; }

    [Column("Section_Title")]
    [StringLength(1000)]
    [Unicode(false)]
    public string SectionTitle { get; set; }

    [Column("Section_Description")]
    [Unicode(false)]
    public string SectionDescription { get; set; }

    [Column("Repo_Link")]
    [StringLength(1000)]
    [Unicode(false)]
    public string RepoLink { get; set; }

    [Column("Display_Order")]
    public int? DisplayOrder { get; set; }

    [Column("Display_Online")]
    public bool? DisplayOnline { get; set; }
}