// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace API_Metadata.Models_DB;

public partial class PageVisit
{
    [Key]
    [Column("PageVisits_ID")]
    public int PageVisitsId { get; set; }

    [Required]
    [Column("Page_Name")]
    [StringLength(500)]
    [Unicode(false)]
    public string PageName { get; set; }

    [Column("Visit_DT", TypeName = "datetime")]
    public DateTime VisitDt { get; set; }
}