// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Reflection.Emit;
using API_Metadata.Models_DB2;
using Microsoft.EntityFrameworkCore;

namespace API_Metadata.Models_DB;

public partial class WebsiteDB_Context : DbContext
{
    public WebsiteDB_Context()
    {
    }

    public WebsiteDB_Context(DbContextOptions<WebsiteDB_Context> options)
        : base(options)
    {
    }

    public virtual DbSet<ApiLogging> ApiLoggings { get; set; }

    public virtual DbSet<GitHub> GitHubs { get; set; }

    public virtual DbSet<PageVisit> PageVisits { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("Website");

        modelBuilder.Entity<ApiLogging>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__API_Logg__9A8D5625A01B4071");
        });

        modelBuilder.Entity<GitHub>(entity =>
        {
            entity.HasKey(e => e.GitHubId).HasName("PK__GitHub__D1B1D1281D2DA2F9");
        });

        modelBuilder.Entity<PageVisit>(entity =>
        {
            entity.HasKey(e => e.PageVisitsId).HasName("PK__PageVisi__3C7AA9E3965D27FA");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}